export const STAGES = [
  { id: 'email',    label: 'Email Received',      color: '#334155', bg: '#f1f5f9' },
  { id: 'ultro',    label: 'Listed & Assigned',   color: '#713f12', bg: '#fef9c3' },
  { id: 'team',     label: 'Team Assigned',        color: '#9a3412', bg: '#fff7ed' },
  { id: 'work',     label: 'Work Initiated',       color: '#4c1d95', bg: '#ede9fe' },
  { id: 'tpay',     label: 'Team Payment',         color: '#6b21a8', bg: '#fdf4ff' },
  { id: 'matrcv',   label: 'Mat. Received',        color: '#065f46', bg: '#ecfdf5' },
  { id: 'packing',  label: 'Packing Done',         color: '#14532d', bg: '#f0fdf4' },
  { id: 'dc',       label: 'DC Received',          color: '#1e40af', bg: '#eff6ff' },
  { id: 'sreq',     label: 'SREQ Done',            color: '#581c87', bg: '#faf5ff' },
  { id: 'matsub',   label: 'Mat. Submitted',       color: '#9a3412', bg: '#fff7ed' },
  { id: 'signdc',   label: 'Signed DC',            color: '#6b21a8', bg: '#fdf4ff' },
  { id: 'po',       label: 'PO Received',          color: '#92400e', bg: '#fffbeb' },
  { id: 'wcc',      label: 'WCC Stage',            color: '#581c87', bg: '#faf5ff' },
  { id: 'invoice',  label: 'Invoice Due',          color: '#881337', bg: '#fff1f2' },
  { id: 'done',     label: 'Completed',            color: '#14532d', bg: '#f0fdf4' },
]

export const STAGE_STEPS = [
  { key: 'email_received_date',   label: 'Email Received',                       fields: ['email_received_date', 'email_content'], isDate: false },
  { key: 'listed_on_ultro',       label: 'Listed & Assigned on Ultro',            fields: ['listed_on_ultro', 'email_sent_to_client'], isYesNo: true },
  { key: 'team_assigned',         label: 'Team Assigned',                         fields: ['team_assigned', 'team_name', 'team_number'], isYesNo: true },
  { key: 'work_initiated',        label: 'Work Initiated',                        fields: ['work_initiated', 'work_date'], isYesNo: true },
  { key: 'advance_amount',        label: 'Team Payment',                          fields: ['advance_amount', 'advance_date', 'advance_mode', 'balance_amount', 'balance_date', 'balance_mode'], isPayment: true },
  { key: 'material_received',     label: 'Material Received at MTNH Warehouse',   fields: ['material_received', 'material_received_date'], isYesNo: true },
  { key: 'packing_done',          label: 'Packing Done',                          fields: ['packing_done', 'packing_date', 'packing_photo_url'], isYesNo: true, hasPhoto: true },
  { key: 'dc_received',           label: 'DC Received',                           fields: ['dc_received', 'dc_number'], isYesNo: true },
  { key: 'sreq_done',             label: 'SREQ Done',                             fields: ['sreq_done', 'sreq_date', 'sreq_number'], isYesNo: true },
  { key: 'material_submitted',    label: 'Material Submitted at Partner Warehouse',fields: ['material_submitted', 'material_submitted_date'], isYesNo: true },
  { key: 'signed_dc_received',    label: 'Signed DC Received',                    fields: ['signed_dc_received', 'signed_dc_date', 'signed_dc_url'], isYesNo: true, hasPdf: true },
  { key: 'po_received',           label: 'PO Received',                           fields: ['po_received', 'po_date', 'po_number'], isYesNo: true, isFlexible: true },
  { key: 'all_tasks_ultro',       label: 'All Ultro Tasks Done',                  fields: ['all_tasks_ultro', 'pending_tasks'], isYesNo: true },
  { key: 'wcc_received',          label: 'WCC Received',                          fields: ['wcc_received', 'wcc_date', 'wcc_number', 'wcc_remark'], isYesNo: true, hasPending: true },
  { key: 'invoice_done',          label: 'Invoice Done',                          fields: ['invoice_done', 'invoice_date', 'invoice_number'], isYesNo: true },
  { key: 'payment_received',      label: 'Payment Received',                      fields: ['payment_received', 'payment_date', 'payment_amount', 'remarks'], isYesNo: true },
]

export const FIELD_LABELS = {
  email_received_date: 'Email Received Date',
  email_content: 'Email Content / Summary',
  listed_on_ultro: 'Listed & Assigned on Ultro',
  email_sent_to_client: 'Email Sent to Client',
  team_assigned: 'Team Assigned',
  team_name: 'Team Name',
  team_number: 'Team Number',
  work_initiated: 'Work Initiated',
  work_date: 'Work Date',
  advance_amount: 'Advance Amount (₹)',
  advance_date: 'Advance Payment Date',
  advance_mode: 'Advance Payment Mode',
  balance_amount: 'Balance Amount (₹)',
  balance_date: 'Balance Payment Date',
  balance_mode: 'Balance Payment Mode',
  material_received: 'Material Received',
  material_received_date: 'Receipt Date',
  packing_done: 'Packing Done',
  packing_date: 'Packing Date',
  packing_photo_url: 'Packing Photo',
  dc_received: 'DC Received',
  dc_number: 'DC Number',
  sreq_done: 'SREQ Done',
  sreq_date: 'SREQ Date',
  sreq_number: 'SREQ Number',
  material_submitted: 'Material Submitted',
  material_submitted_date: 'Submission Date',
  signed_dc_received: 'Signed DC Received',
  signed_dc_date: 'Signed DC Date',
  signed_dc_url: 'Signed DC (PDF)',
  po_received: 'PO Received',
  po_date: 'PO Date',
  po_number: 'PO Number',
  all_tasks_ultro: 'All Ultro Tasks Done',
  pending_tasks: 'Pending Tasks',
  wcc_received: 'WCC Received',
  wcc_date: 'WCC Date',
  wcc_number: 'WCC Number',
  wcc_remark: 'WCC Pending Reason',
  invoice_done: 'Invoice Done',
  invoice_date: 'Invoice Date',
  invoice_number: 'Invoice Number',
  payment_received: 'Payment Received',
  payment_date: 'Payment Date',
  payment_amount: 'Payment Amount (₹)',
  remarks: 'Closing Remarks',
}

export const PAYMENT_MODES = [
  'UPI — Company Account',
  'UPI — Personal Account',
  'Cash',
]

// Sheet export headers
export const SHEET_HEADERS = [
  'Site ID', 'Site Name', 'Zone', 'City', 'Circle', 'Site Type', 'Toco', 'Layer',
  'Email Date', 'Email Content',
  'Listed on Ultro', 'Email Sent to Client',
  'Team Assigned', 'Team Name', 'Team Number',
  'Work Initiated', 'Work Date',
  'Advance Amount', 'Advance Date', 'Advance Mode',
  'Balance Amount', 'Balance Date', 'Balance Mode',
  'Material Received', 'Material Received Date',
  'Packing Done', 'Packing Date',
  'DC Received', 'DC Number',
  'SREQ Done', 'SREQ Date', 'SREQ Number',
  'Material Submitted', 'Submission Date',
  'Signed DC Received', 'Signed DC Date',
  'PO Received', 'PO Date', 'PO Number',
  'All Ultro Tasks', 'Pending Tasks',
  'WCC Received', 'WCC Date', 'WCC Number', 'WCC Remark',
  'Invoice Done', 'Invoice Date', 'Invoice Number',
  'Payment Received', 'Payment Date', 'Payment Amount',
  'Remarks', 'Stage', 'Last Updated',
]

export function projectToSheetRow(p, stageName) {
  return [
    p.site_id, p.site_name, p.zone, p.city, p.circle, p.site_type, p.toco, p.layer,
    p.email_received_date, p.email_content,
    p.listed_on_ultro, p.email_sent_to_client,
    p.team_assigned, p.team_name, p.team_number,
    p.work_initiated, p.work_date,
    p.advance_amount, p.advance_date, p.advance_mode,
    p.balance_amount, p.balance_date, p.balance_mode,
    p.material_received, p.material_received_date,
    p.packing_done, p.packing_date,
    p.dc_received, p.dc_number,
    p.sreq_done, p.sreq_date, p.sreq_number,
    p.material_submitted, p.material_submitted_date,
    p.signed_dc_received, p.signed_dc_date,
    p.po_received, p.po_date, p.po_number,
    p.all_tasks_ultro, p.pending_tasks,
    p.wcc_received, p.wcc_date, p.wcc_number, p.wcc_remark,
    p.invoice_done, p.invoice_date, p.invoice_number,
    p.payment_received, p.payment_date, p.payment_amount,
    p.remarks, stageName, new Date().toISOString(),
  ]
}
